from get_drunk_telegram_bot.model.abstract import IModel
from get_drunk_telegram_bot.model.base import BaseModel
from get_drunk_telegram_bot.model.predictor import EmbederModel
from get_drunk_telegram_bot.model.stsbert import STSBertCocktailModel
